on: workflow_dispatch
name: Build libcec
jobs:
  build-libcec:
    name: Build libcec
    runs-on: armv7-raspi
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install libcec(-dev) and build dependencies
        run: |
            set -ex
            sudo apt-get update
            sudo apt install -yq libp8-platform-dev libp8-platform2 cmake libudev-dev libxrandr-dev python3-dev swig git
      - name: Build libcec (with RPi feature, unlike the one from apt repo)
        run: |
            sudo rm -rf /tmp/libcec-build-tmp
            sudo mkdir /tmp/libcec-build-tmp
            sudo git clone --recursive https://github.com/Pulse-Eight/libcec.git /tmp/libcec-build-tmp/libcec
            sudo sh -c "cd /tmp/libcec-build-tmp/libcec && sudo git checkout libcec-6.0.2"
            sudo mkdir /tmp/libcec-build-tmp/libcec/build
            sudo sh -c "cd /tmp/libcec-build-tmp/libcec/build && sudo cmake -DRPI_INCLUDE_DIR=/opt/vc/include -DRPI_LIB_DIR=/opt/vc/lib .."
            sudo sh -c "cd /tmp/libcec-build-tmp/libcec/build && sudo make -j4"
            #sudo sh -c "cd /tmp/libcec-build-tmp/libcec/build && sudo make install"
            #sudo ldconfig